services:
  backend:
    image: php-crm-laravel-angular-backend:latest
    restart: unless-stopped
    container_name: backend
    volumes:
      - ./api-crm-erp:/var/www/html
      - ./api-crm-erp/.env:/var/www/html/.env
    ports:
      - "8000:80"
    networks:
      - app_network

  frontend:
    image: php-crm-laravel-angular-frontend:latest
    restart: unless-stopped
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge